# Generated by Django 2.2.9 on 2020-01-23 09:02

import datetime
from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_auto_20200113_1721"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2020, 1, 23, 9, 2, 31, 966823, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="created",
            ),
        ),
    ]
