# Generated by Django 3.2.18 on 2023-05-25 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0037_auto_20230425_1512"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltool",
            name="disclaimer",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="disclaimer",
        ),
    ]
