# Generated by Django 3.2.18 on 2023-05-26 07:34

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("content", "0038_auto_20230525_1424"),
    ]

    operations = [
        migrations.AddField(
            model_name="potential",
            name="icon_white",
            field=filer.fields.image.FilerImageField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Icon weiß",
            ),
        ),
    ]
