# Generated by Django 4.2.3 on 2023-07-05 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0037_auto_20230508_1123"),
        ("content", "0039_potential_icon_white"),
    ]

    operations = []
