# Generated by Django 4.2.3 on 2023-12-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_auto_20230508_1123"),
    ]

    operations = [
        migrations.AddField(
            model_name="dlluser",
            name="personal_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dlluser",
            name="terms_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
