# Generated by Django 3.2.18 on 2023-05-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0008_review_comm_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coauthorshipinvitation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="communicationevent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="communicationeventtype",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="newslettersubscrption",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
